stages:
    - setup
    - test
    - package

variables:
    MYSQL_ROOT_PASSWORD: shopware
    MYSQL_ROOT_HOST: '%'
    MYSQL_DATABASE: shopware
    MYSQL_USER: shopware
    MYSQL_PASSWORD: shopware
    PLUGIN_NAME: HeidelPayment6
    SHOPWARE_VERSION: "v6.1.3" # Tag

cache:
    key: "$PLUGIN_NAME-$CI_COMMIT_REF_SLUG"

composer:
    stage: setup
    image: "edbizarro/gitlab-ci-pipeline-php:7.2"
    script:
        - composer install --prefer-dist --no-ansi --no-interaction --no-progress --optimize-autoloader
    artifacts:
        paths:
            - vendor/
        expire_in: 1 days
        when: always
    cache:
        paths:
            - vendor/

phpstan:
    stage: test
    image: "edbizarro/gitlab-ci-pipeline-php:7.2"
    dependencies:
        - composer
    script:
        - git clone -b ${SHOPWARE_VERSION} https://github.com/shopware/development "${CI_PROJECT_DIR}/opt/shopware"
        - rmdir "${CI_PROJECT_DIR}/opt/shopware/platform"
        - git clone -b ${SHOPWARE_VERSION} https://github.com/shopware/platform "${CI_PROJECT_DIR}/opt/shopware/platform"
        - mv ${CI_PROJECT_DIR}/opt /tmp/opt
        - cp -r ${CI_PROJECT_DIR} /tmp/opt/shopware/custom/plugins/${PLUGIN_NAME}
        - mv /tmp/opt ${CI_PROJECT_DIR}/opt
        - cd ${CI_PROJECT_DIR}/opt/shopware && composer install --no-interaction --optimize-autoloader --no-suggest --no-scripts
        - cd ${CI_PROJECT_DIR}/opt/shopware && composer dump-autoload -d custom/plugins/${PLUGIN_NAME}
        - cd ${CI_PROJECT_DIR}/opt/shopware/custom/plugins/${PLUGIN_NAME} && vendor/bin/phpstan analyse -c phpstan.neon --autoload-file=${CI_PROJECT_DIR}/opt/shopware/vendor/autoload.php src

codestyle:
    stage: test
    image: "edbizarro/gitlab-ci-pipeline-php:7.2"
    dependencies:
        - composer
    script:
        - vendor/bin/php-cs-fixer fix -v --dry-run
    cache:
        key: global
        paths:
            - .php_cs.cache
package:
    image: kellerkinder/shopware-package-plugin:latest
    stage: package
    only:
        - master
    script:
        - package-plugin
    artifacts:
        paths:
            - $PLUGIN_NAME.zip
